# Generated by Django 3.2.7 on 2021-10-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('system', models.CharField(max_length=40)),
                ('subsystem', models.CharField(max_length=40)),
                ('user', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True)),
                ('max_rf', models.IntegerField(default=-60)),
                ('min_rf', models.IntegerField(default=-100)),
                ('max_aud', models.IntegerField(default=0)),
                ('min_aud', models.IntegerField(default=-40)),
                ('max_gain', models.IntegerField(default=10)),
                ('min_gain', models.IntegerField(default=-18)),
            ],
            options={
                'verbose_name_plural': 'models',
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Mics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('alias', models.CharField(blank=True, max_length=20)),
                ('detail', models.CharField(max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.devices')),
            ],
            options={
                'verbose_name_plural': 'mics',
                'db_table': 'mics',
            },
        ),
        migrations.CreateModel(
            name='GroupExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('mics', models.ManyToManyField(blank=True, to='backend.Mics')),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.models'),
        ),
    ]
